### ISSUE TITLE
starting btcd causes panic

### ISSUE THREAD

**Issue by michaltakac** [Roasbeef/btcd#18]
When I try to start `btcd`, I get following output:

```
2018-03-18 12:48:51.356 [INF] BTCD: Version 0.12.0-beta
2018-03-18 12:48:51.368 [INF] BTCD: Loading block database from '/crypto/btc-data/testnet/blocks_ffldb'
2018-03-18 12:48:51.425 [INF] BTCD: Block database loaded
2018-03-18 12:48:51.428 [INF] INDX: cf index is enabled
2018-03-18 12:48:51.429 [INF] CHAN: Loading block index.  This might take a while...
2018-03-18 12:48:51.567 [INF] BTCD: Gracefully shutting down the database...
2018-03-18 12:48:51.567 [INF] BTCD: Shutdown complete
panic: runtime error: slice bounds out of range [recovered]
	panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/roasbeef/btcd/database/ffldb.rollbackOnPanic(0xc4201c4240)
	/home/mike/projects/go/src/github.com/roasbeef/btcd/database/ffldb/db.go:1889 +0x77
panic(0x99e4e0, 0xeb00e0)
	/usr/local/go/src/runtime/panic.go:505 +0x229
github.com/roasbeef/btcd/database/ffldb.(*transaction).FetchBlockHeader(0xc4201c4240, 0xc4200226c0, 0x89a0650, 0x20, 0xc420022280, 0xc4200200e0, 0xc4200226c0)
	/home/mike/projects/go/src/github.com/roasbeef/btcd/database/ffldb/db.go:1278 +0x2bc
github.com/roasbeef/btcd/blockchain.dbFetchHeaderByHash(0xbff0a0, 0xc4201c4240, 0xc4200226c0, 0xc4200226c0, 0x0, 0x0)
	/home/mike/projects/go/src/github.com/roasbeef/btcd/blockchain/chainio.go:1231 +0x3f
github.com/roasbeef/btcd/blockchain.dbFetchHeaderByHeight(0xbff0a0, 0xc4201c4240, 0x0, 0xc421938000, 0x13a933, 0x13a933)
	/home/mike/projects/go/src/github.com/roasbeef/btcd/blockchain/chainio.go:1253 +0x8f
github.com/roasbeef/btcd/blockchain.(*BlockChain).initChainState.func1(0xbff0a0, 0xc4201c4240, 0xc4201c4240, 0x0)
	/home/mike/projects/go/src/github.com/roasbeef/btcd/blockchain/chainio.go:1159 +0x37d
github.com/roasbeef/btcd/database/ffldb.(*db).View(0xc4200aa440, 0xc4204ea340, 0x0, 0x0)
	/home/mike/projects/go/src/github.com/roasbeef/btcd/database/ffldb/db.go:1912 +0x9b
github.com/roasbeef/btcd/blockchain.(*BlockChain).initChainState(0xc4204d1200, 0xc4204d1200, 0xc42022f728)
	/home/mike/projects/go/src/github.com/roasbeef/btcd/blockchain/chainio.go:1134 +0x99
github.com/roasbeef/btcd/blockchain.New(0xc4201f8310, 0xc4201f8310, 0xb, 0x0)
	/home/mike/projects/go/src/github.com/roasbeef/btcd/blockchain/chain.go:1600 +0x528
main.newServer(0xc420097350, 0x1, 0x1, 0xbfbb40, 0xc4200aa440, 0xeb9300, 0xc42008c120, 0xc4204ea680, 0xc4204ea660, 0xc4200970c0)
	/home/mike/projects/go/src/github.com/roasbeef/btcd/server.go:2412 +0x8d9
main.btcdMain(0x0, 0x0, 0x0)
	/home/mike/projects/go/src/github.com/roasbeef/btcd/btcd.go:148 +0x686
main.main()
	/home/mike/projects/go/src/github.com/roasbeef/btcd/btcd.go:330 +0xd0
```

When I use `btcd` from `btcsuite`, I don't get this error and node starts normally.

`go version go1.10 linux/amd64`

**Comment by Roasbeef** [comment]
The index structure between this fork, and the `btcsuite` version has diverged, so for now (until I catch up to upstream) they aren't _strictly_ interchangeable.

**Comment by deafboy** [comment]
>The index structure between this fork, and the btcsuite version has diverged

I've never run the btcsuite version and I'm still affected by this. Did you introduce a breaking change recently, requiring the chain rescan? This is no joke because it took me 2 weeks last time. :)


```
[bitcoin@lnd btcd]$ btcd
2018-04-08 16:19:35.402 [INF] BTCD: Version 0.12.0-beta
2018-04-08 16:19:35.402 [INF] BTCD: Loading block database from '/home/bitcoin/.btcd/data/mainnet/blocks_ffldb'
2018-04-08 16:19:36.023 [INF] BTCD: Block database loaded
2018-04-08 16:19:36.040 [INF] INDX: Transaction index is enabled
2018-04-08 16:19:36.040 [INF] INDX: cf index is enabled
2018-04-08 16:19:36.040 [INF] CHAN: Loading block index.  This might take a while...
2018-04-08 16:20:24.183 [INF] CHAN: Chain state (height 517228, hash 00000000000000000040e559ba73e3143b8fd4885aefad1f273644bb4faf26fa, totaltx 309032803, work 449605813364450917024261045)
2018-04-08 16:20:24.408 [INF] RPCS: RPC server listening on 127.0.0.1:8334
2018-04-08 16:20:25.324 [INF] AMGR: Loaded 44840 addresses from file '/home/bitcoin/.btcd/data/mainnet/peers.json'
2018-04-08 16:20:25.326 [INF] CMGR: Server listening on 0.0.0.0:8333
2018-04-08 16:20:25.326 [INF] CMGR: Server listening on [::]:8333
2018-04-08 16:20:25.328 [INF] SYNC: New valid peer 192.168.1.171:44908 (inbound) (/Satoshi:0.16.0/)
2018-04-08 16:20:25.329 [INF] SYNC: Syncing to block height 517233 from peer 192.168.1.171:44908
2018-04-08 16:20:25.329 [INF] SYNC: New valid peer 128.235.40.191:25055 (inbound) (/btc.cs.njit.edu:0.1/)
2018-04-08 16:20:25.329 [INF] CMGR: 40 addresses found from DNS seed seed.bitcoin.sipa.be
2018-04-08 16:20:25.334 [INF] CMGR: 38 addresses found from DNS seed dnsseed.bitcoin.dashjr.org
2018-04-08 16:20:25.329 [INF] SYNC: New valid peer 136.243.139.96:49228 (inbound) (/bitnodes.earn.com:0.1/)
2018-04-08 16:20:25.336 [INF] SYNC: New valid peer 136.243.139.96:4191 (inbound) (/bitnodes.earn.com:0.1/)
2018-04-08 16:20:25.336 [INF] CMGR: 38 addresses found from DNS seed seed.bitcoin.jonasschnelli.ch
2018-04-08 16:20:25.336 [INF] SYNC: Lost peer 128.235.40.191:25055 (inbound)
2018-04-08 16:20:25.336 [INF] SYNC: Lost peer 136.243.139.96:49228 (inbound)
2018-04-08 16:20:25.372 [INF] SYNC: New valid peer 94.130.64.167:8333 (outbound) (/Satoshi:0.15.99/)
2018-04-08 16:20:25.377 [INF] SYNC: New valid peer 91.121.144.57:8333 (outbound) (/Satoshi:0.14.2(UASF-SegWit-BIP148; UASF-SegWit-BIP148)/UASF-Segwit:1.0(BIP148)/)
2018-04-08 16:20:25.386 [INF] CMGR: 40 addresses found from DNS seed seed.bitnodes.io
2018-04-08 16:20:25.409 [INF] SYNC: New valid peer 54.77.96.42:8333 (outbound) (/Bitcoin ABC:0.16.1(EB8.0)/)
2018-04-08 16:20:25.409 [INF] PEER: Disconnecting non-segwit peer 54.77.96.42:8333 (outbound), isn't segwit enabled and we need more segwit enabled peers
2018-04-08 16:20:25.409 [INF] SYNC: Lost peer 54.77.96.42:8333 (outbound)
2018-04-08 16:20:25.461 [INF] CMGR: 33 addresses found from DNS seed dnsseed.bluematt.me
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x783353]

goroutine 13 [running]:
github.com/roasbeef/btcd/database/ffldb.rollbackOnPanic(0xc42055e090)
	/home/bitcoin/.go/src/github.com/roasbeef/btcd/database/ffldb/db.go:1889 +0x77
panic(0x99c960, 0xeae0d0)
	/usr/lib/go-1.10/src/runtime/panic.go:505 +0x229
github.com/roasbeef/btcd/blockchain/indexers.dbStoreFilterIdxEntry(0xbfda80, 0xc42055e090, 0xe7ee80, 0x10, 0x10, 0xc4295e57c0, 0xc42fec43a0, 0x20, 0x20, 0x0, ...)
	/home/bitcoin/.go/src/github.com/roasbeef/btcd/blockchain/indexers/cfindex.go:71 +0xb3
github.com/roasbeef/btcd/blockchain/indexers.storeFilter(0xbfda80, 0xc42055e090, 0xc4282d1b20, 0xc42e721620, 0x0, 0x24, 0xc430801320)
	/home/bitcoin/.go/src/github.com/roasbeef/btcd/blockchain/indexers/cfindex.go:171 +0x2b1
github.com/roasbeef/btcd/blockchain/indexers.(*CfIndex).ConnectBlock(0xc4201623c0, 0xbfda80, 0xc42055e090, 0xc4282d1b20, 0xc4282020f0, 0xc430955320, 0x7e46c)
	/home/bitcoin/.go/src/github.com/roasbeef/btcd/blockchain/indexers/cfindex.go:212 +0x76
github.com/roasbeef/btcd/blockchain/indexers.dbIndexConnectBlock(0xbfda80, 0xc42055e090, 0xbfb680, 0xc4201623c0, 0xc4282d1b20, 0xc4282020f0, 0x0, 0x0)
	/home/bitcoin/.go/src/github.com/roasbeef/btcd/blockchain/indexers/manager.go:87 +0x128
github.com/roasbeef/btcd/blockchain/indexers.(*Manager).ConnectBlock(0xc420cf1f80, 0xbfda80, 0xc42055e090, 0xc4282d1b20, 0xc4282020f0, 0x15e3, 0x0)
	/home/bitcoin/.go/src/github.com/roasbeef/btcd/blockchain/indexers/manager.go:535 +0xa0
github.com/roasbeef/btcd/blockchain.(*BlockChain).connectBlock.func1(0xbfda80, 0xc42055e090, 0xc42055e090, 0x0)
	/home/bitcoin/.go/src/github.com/roasbeef/btcd/blockchain/chain.go:647 +0x1d6
github.com/roasbeef/btcd/database/ffldb.(*db).Update(0xc42015c200, 0xc42dfb6000, 0x0, 0x0)
	/home/bitcoin/.go/src/github.com/roasbeef/btcd/database/ffldb/db.go:1946 +0x9b
github.com/roasbeef/btcd/blockchain.(*BlockChain).connectBlock(0xc4204e7e00, 0xc42a5af960, 0xc4282d1b20, 0xc4282020f0, 0xc42ea4e000, 0x15e3, 0x15e3, 0x0, 0xe200000000000003)
	/home/bitcoin/.go/src/github.com/roasbeef/btcd/blockchain/chain.go:614 +0x2f8
github.com/roasbeef/btcd/blockchain.(*BlockChain).connectBestChain(0xc4204e7e00, 0xc42a5af960, 0xc4282d1b20, 0xc400000000, 0x0, 0x0, 0xc42df9dad8)
	/home/bitcoin/.go/src/github.com/roasbeef/btcd/blockchain/chain.go:1072 +0x1de
github.com/roasbeef/btcd/blockchain.(*BlockChain).maybeAcceptBlock(0xc4204e7e00, 0xc4282d1b20, 0xffffffff00000000, 0x0, 0x0, 0xec30c0)
	/home/bitcoin/.go/src/github.com/roasbeef/btcd/blockchain/accept.go:78 +0x21b
github.com/roasbeef/btcd/blockchain.(*BlockChain).ProcessBlock(0xc4204e7e00, 0xc4282d1b20, 0xc400000000, 0xc42d4c0000, 0x0, 0x0)
	/home/bitcoin/.go/src/github.com/roasbeef/btcd/blockchain/process.go:228 +0x2b5
github.com/roasbeef/btcd/netsync.(*SyncManager).handleBlockMsg(0xc420186420, 0xc420f922c0)
	/home/bitcoin/.go/src/github.com/roasbeef/btcd/netsync/manager.go:569 +0x205
github.com/roasbeef/btcd/netsync.(*SyncManager).blockHandler(0xc420186420)
	/home/bitcoin/.go/src/github.com/roasbeef/btcd/netsync/manager.go:1152 +0x548
created by github.com/roasbeef/btcd/netsync.(*SyncManager).Start
	/home/bitcoin/.go/src/github.com/roasbeef/btcd/netsync/manager.go:1374 +0xe3
[bitcoin@lnd btcd]$
```

**Comment by deafboy** [comment]
Reverted to commit b0bc7fcb951bed421d53ea94c58f5ccce93a2d3d. Seems to work fine.
