### ISSUE TITLE
SYNC: Failed to process block

### ISSUE THREAD

**Issue by Liongrass** [Roasbeef/btcd#24]
I'm syncing btcd on Ubuntu 18.04 LTS 4.15.0-20-generic.

I'm using the command `~$ go/bin/btcd --testnet --txindex`
I see btcd crashing repeatedly with the following errors:

`2018-05-15 21:38:52.345 [ERR] SYNC: Failed to process block 0000000000000789d01477f37ef86ffec951d0ca2192d761a5068878610e8649: failed to open ldb transaction: leveldb/table: corruption on data-block (pos=1827711): checksum mismatch, want=0x15ca319f got=0x4df6a1cc [file=094552.ldb]
panic: failed to open ldb transaction: leveldb/table: corruption on data-block (pos=1827711): checksum mismatch, want=0x15ca319f got=0x4df6a1cc [file=094552.ldb]`

`2018-05-15 21:45:18.267 [ERR] SYNC: Failed to process block 00000000000cae5e5b78982e6eb20532ce3bdf41f4df1580f628d9c9c03b9844: failed to open ldb transaction: leveldb/table: corruption on data-block (pos=1827711): checksum mismatch, want=0x15ca319f got=0x4df6a1cc [file=094552.ldb]
panic: failed to open ldb transaction: leveldb/table: corruption on data-block (pos=1827711): checksum mismatch, want=0x15ca319f got=0x4df6a1cc [file=094552.ldb]`

`2018-05-15 21:52:53.502 [ERR] SYNC: Failed to process block 00000000000003805e0815351d0181e6495047379b2748f8f6697c2b8ea512a7: failed to open ldb transaction: leveldb/table: corruption on data-block (pos=1827711): checksum mismatch, want=0x15ca319f got=0x4df6a1cc [file=094552.ldb]
panic: failed to open ldb transaction: leveldb/table: corruption on data-block (pos=1827711): checksum mismatch, want=0x15ca319f got=0x4df6a1cc [file=094552.ldb]`

`2018-05-15 21:58:41.809 [ERR] SYNC: Failed to process block 0000000000000789d01477f37ef86ffec951d0ca2192d761a5068878610e8649: failed to open ldb transaction: leveldb/table: corruption on data-block (pos=1827711): checksum mismatch, want=0x15ca319f got=0x4df6a1cc [file=094552.ldb]
panic: failed to open ldb transaction: leveldb/table: corruption on data-block (pos=1827711): checksum mismatch, want=0x15ca319f got=0x4df6a1cc [file=094552.ldb]`

Also part of the error log:

`goroutine 39 [running]:
github.com/roasbeef/btcd/netsync.(*SyncManager).handleBlockMsg(0xc4200f04d0, 0xc43e261960)
	/home/loysan/go/src/github.com/roasbeef/btcd/netsync/manager.go:584 +0x1430
github.com/roasbeef/btcd/netsync.(*SyncManager).blockHandler(0xc4200f04d0)
	/home/loysan/go/src/github.com/roasbeef/btcd/netsync/manager.go:1152 +0x548
created by github.com/roasbeef/btcd/netsync.(*SyncManager).Start
	/home/loysan/go/src/github.com/roasbeef/btcd/netsync/manager.go:1374 +0xe3`

**Comment by molxyz** [comment]
@Liongrass Have you been able to get your btcd node to work?  The current repo for btcd source is no longer roasbeefs fork but this site:   https://github.com/btcsuite/btcd#installation.

**Comment by Liongrass** [comment]
I have to admit I gave up on it.
